version: 2.1

orbs:
  nx: nrwl/nx@1.6.1
  codecov: codecov/codecov@3.2.5
  docker: circleci/docker@2.2.0
  doctl: digitalocean/cli@1.0.0

jobs:
  agent:
    docker:
      - image: cimg/node:lts-browsers
    parameters:
      ordinal:
        type: integer
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Start the agent << parameters.ordinal >>
          command: npx nx-cloud start-agent
          no_output_timeout: 60m
  main:
    docker:
      - image: cimg/node:lts-browsers
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - nx/set-shas:
          main-branch-name: 'master'
      - run:
          name: Initialize the Nx Cloud distributed CI run
          command: npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      - run:
          name: Run lint
          command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
      - run:
          name: Run test
          command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage
      - codecov/upload
      - run:
          name: Run build
          command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
      - docker/check
      - docker/build:
          image: ricochetbrown7/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          digest-path: /tmp/digest.txt
          image: ricochetbrown7/$CIRCLE_PROJECT_REPONAME
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      - doctl/install_and_initialize_cli:
          executor: doctl/default
      - run:
          name: SSH into Droplet
          command: doctl compute ssh against-all-odds
      - run:
          name: Run docker
          command: docker run -d -p 80:80 ricochetbrown7/$CIRCLE_PROJECT_REPONAME
      - run:
          name: Stop all agents
          command: npx nx-cloud stop-all-agents
          when: always

workflows:
  version: 2

  circleci:
    jobs:
      - agent:
          name: Nx Cloud Agent << matrix.ordinal >>
          matrix:
            parameters:
              ordinal: [1, 2, 3]
      - main:
          name: Nx Cloud Main
